name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Fix Biome permissions
        run: chmod +x node_modules/.pnpm/@biomejs+cli-linux-x64@*/node_modules/@biomejs/cli-linux-x64/biome
        
      - name: Run linter
        run: pnpm run lint
        
      - name: Run type check
        run: pnpm exec tsc --noEmit
        
      - name: Run tests
        run: pnpm run test
        
      - name: Build project
        run: pnpm run build
        env:
          NODE_ENV: development
          DATABASE_URL: postgresql://postgres:password@localhost:5432/test_db
        
      - name: Build Docker image for validation
        run: |
          docker build --tag preview-build:${{ github.sha }} .
          
      - name: Add validation summary
        run: |
          echo "## ✅ PR Validation Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: All checks passed" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **PR**: #${{ github.event.number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Validated at**: $(date)" >> $GITHUB_STEP_SUMMARY

